
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HR_To_AWS
{

using System;
    using System.Collections.Generic;
    
public partial class AWS_PRAC_WEKTOR
{

    public int id { get; set; }

    public Nullable<int> status { get; set; }

    public Nullable<int> holl_days { get; set; }

    public int id_prac { get; set; }

    public Nullable<int> ill_days { get; set; }

    public Nullable<int> work_days { get; set; }

    public int year { get; set; }

    public int month { get; set; }

}

}
