

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HR_To_AWS
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class DEMO_KD_1Entities : DbContext
{
    public DEMO_KD_1Entities()
        : base("name=DEMO_KD_1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AWS_PRAC_WEKTOR> AWS_PRAC_WEKTOR { get; set; }


    public virtual int AWS_PRAC_TO_VECTOR()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AWS_PRAC_TO_VECTOR");
    }

}

}

